apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: contour-app
  namespace: argocd
spec:
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: projectcontour
  project: space-project
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
  source:
    repoURL: https://github.com/space-devops/kustomize-services
    path: ./contour/overlays/base-install
    targetRevision: HEAD