apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: istioaddons-app
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "4"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: istio-system
  project: space-project
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
  source:
    repoURL: https://github.com/space-devops/kustomize-services
    path: ./istio-addons/overlays/dev
    targetRevision: HEAD
