apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mountebank-server-app
  namespace: argocd
spec:
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: mountebank
  project: space-project
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
  source:
    repoURL: https://github.com/space-devops/kustomize-services
    path: ./mountebank-server/overlays/dev/
    targetRevision: HEAD
