apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: space-project
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  description: "Space Devops Project"
  sourceRepos:
    - '*'
  destinations:
    - namespace: argocd
      server: https://kubernetes.default.svc
    - namespace: mountebank
      server: https://kubernetes.default.svc
    - namespace: projectcontour
      server: https://kubernetes.default.svc
    - namespace: sealed-secrets
      server: https://kubernetes.default.svc