apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: space-project
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  description: "Space Devops Project"
  sourceRepos:
    - '*'